### ISSUE TITLE
Package name adjustment to follow PEP8

### ISSUE THREAD

**Issue by radziej** [AnotherSamWilson/miceforest#1]
Hi Sam,

great package! Especially love the detailed documentation. I was wondering whether you would consider renaming the Python package in order to follow the PEP8 convention [1]? I think something like `miceforest` would be great.

[1]https://www.python.org/dev/peps/pep-0008/#id40

**Comment by AnotherSamWilson** [comment]
Closed with a rename. PyPi package matches.
