### ISSUE TITLE
Allow custom mean-matching functions

### ISSUE THREAD

**Issue by samFarrellDay** [AnotherSamWilson/miceforest#11]
Nearest neighbors search can be optimized for specific situations and machines. It would be a good idea to allow the user to specify a mean matching function if they don't want to rely on the default sklearn NearestNeighbors implementation. Over several million candidates, faiss is much faster.

**Comment by AnotherSamWilson** [comment]
Closed by 424c926eff8be2f590a0a816809ea5fb23da1998
