### ISSUE TITLE
Process finished with exit code -1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by samFarrellDay** [AnotherSamWilson/miceforest#21]
Getting this reliably. Chased it down to scipy.Spatial.KDtree. Changing leafsize doesn't help. candidate_preds is float64, shape (294695, 1).

**Comment by samFarrellDay** [comment]
Changing to float32 does nothing. Setting mms = 0.5 fixed the issue. Worried there might be a upper limit to the candidates that KDtree can handle.

**Comment by AnotherSamWilson** [comment]
Link to scipy issue. Temporary fix is to use `balanced_tree=False`.
https://github.com/scipy/scipy/issues/14799

**Comment by samFarrellDay** [comment]
Still getting this error for data with lots of duplicate candidate_preds.

**Comment by AnotherSamWilson** [comment]
Haven't seen this error in a while, going to close the issue for now.
