### ISSUE TITLE
Allow generation of imputation values on command

### ISSUE THREAD

**Issue by samFarrellDay** [AnotherSamWilson/miceforest#25]
Actually storing the latest imputation values can take up a lot of memory. We have all the information we need to generate imputation values when complete_data() is called, why not give the user that option.

Easiest way would be to change save_all_iterations to an int parameter. 0=generate on demand, 1 = save latest iteration, 2=save all iterations.

**Comment by AnotherSamWilson** [comment]
Not going to do this.
