### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'balanced_tree'

### ISSUE THREAD

**Issue by micaelamaria** [AnotherSamWilson/miceforest#30]
Hi, 
I am running the following
# Create kernels
kernel = mf.ImputationKernel(
  data=df_empty_amp,
  save_all_iterations=True,
  random_state=123
)
kernel.mice(5, verbose=True)

and keep getting the same error_: TypeError: __init__() got an unexpected keyword argument 'balanced_tree'
Would you know why?

**Comment by AnotherSamWilson** [comment]
scipy needs to be updated, balanced_tree was introduced in 1.6 or so.
