### ISSUE TITLE
Memory usage for categorical data with large numbers of unique values

### ISSUE THREAD

**Issue by magnate64** [AnotherSamWilson/miceforest#36]
I have a categorical feature that has about 8000 unique values and that's causing memory issues to the point where the machine I'm using keep failing. If I get rid of that feature it works great. Any workarounds to still using that column?

**Comment by AnotherSamWilson** [comment]
This will happen with the way lightgbm handles categorical data. 8000 is too many categories. You might want to encode them as numeric somehow or group most of them together. These things are data specific, so I can't help much more than that.
