### ISSUE TITLE
Allow compilation of candidate predictions

### ISSUE THREAD

**Issue by samFarrellDay** [AnotherSamWilson/miceforest#46]
This is an easy win to greatly speed up impute_new_data, and wouldn't cost much memory. Booster._Booster__inner_predict requires a constructed training set, which are not saved with the model when serialized, so that's a no go.

Feasible to store predictions as dynamic datatypes? Experiment with:

- Binary = float16
- Categorical = float16
- Regression = pandas column datatype, allows user to choose precision.

**Comment by AnotherSamWilson** [comment]
Added with 8495ed9dab5b608aaf014df7ffd53f2c19395c58
