### ISSUE TITLE
Complex imputation schema

### ISSUE THREAD

**Issue by neuro30** [AnotherSamWilson/miceforest#58]
This is more of a message board enquiry, but I would like to create an schema where each feature (thousands) is modeled by specific features. Here is your original example from the miceforest documentation:

`# Define which variables should be used to model others `
```
variable_schema = {
    'sepal width (cm)': ['species','petal width (cm)'],
    'petal width (cm)': ['species','sepal length (cm)']
}
```

However, I have thousands of features, each to be modeled from features of that group:

```
feature_group_1
"cg00121626" "cg00223952" "cg00271873" "cg00311963" "cg00335297" "cg00543493" "cg00903245" "cg01086462" "cg01426558"
 "cg01463110" "cg01644972" "cg01911472" 
```

```
feature_group_2
"cg00035864" "cg00061679" "cg00308367" "cg00479827" "cg00576139" "cg00676506" "cg00762184" "cg01053349" "cg01073572"
"cg01311227" "cg01375382" "cg01757887" "cg01828798" "cg01900066" "cg01943289" "cg01984154" "cg02012379" "cg02056550"
"cg02352633" "cg02407581" "cg02522936" "cg03515901" "cg03769088" "cg03905640" "cg03930849" "cg04351468" "cg04477336"
"cg04831594" "cg05098815"
```

How might I set up the variable_schema to reflect this complex design (e.g., cg00121626 is modeled by the other feature_1 features, cg00223952 the same, and so on; same design for other feature groups)? I am most familiar with R, but need to use miceforest to leverage gpus.

Thanks and any help would be great.

**Comment by AnotherSamWilson** [comment]
Sorry for the late reply on this, I was in the mountains for a while. What you're looking for is probably most easily done using Dict Comprehension and regex. This isn't a miceforest specific issue unfortunately, so I'm going to close this issue.
