### ISSUE TITLE
How to cite your work?

### ISSUE THREAD

**Issue by awmmmm** [AnotherSamWilson/miceforest#68]

**Comment by AnotherSamWilson** [comment]
Thanks for pushing me to do this - I have added a DOI to make it easy. You can find the DOI in the badges section, I'll add a citation section to the README soon.

**Comment by cddesja** [comment]
@awmmmm I am using the following BibTeX entry:

@misc{wilson_miceforest_2023,
	title = {miceforest},
	url = {https://github.com/AnotherSamWilson/miceforest/},
	author = {Wilson, Samuel Von and Cebere, Bogdan and Myatt, James and Wilson, Samuel},
	year = {2023},
}

I am happy to update this based on what @AnotherSamWilson suggests.
