### ISSUE TITLE
plot_mean_convergence subplots are numbered, not named

### ISSUE THREAD

**Issue by gorj-tessella** [AnotherSamWilson/miceforest#76]
Each subplot in `plot_mean_convergence` is labeled with the feature index, not the feature name, as of version 5.6.3.  This is because the features are internally specified by the `num_vars` variable, which is the feature index, without converting to the feature name with `self._get_var_name_from_scalar(var)`.

https://github.com/AnotherSamWilson/miceforest/blob/d9359a89204e3b5f10cc02e7e621a22c213e5453/miceforest/ImputedData.py#L549-L552

**Comment by AnotherSamWilson** [comment]
Keeping this issue open as a placeholder for adding the `plot_mean_convergence` function back to the package soon.

**Comment by AnotherSamWilson** [comment]
Fixed in fcf447ee5f6294af2c915bdd5244100cd7d4a638
