### ISSUE TITLE
Optional support by XGBoost for easier GPU integration

### ISSUE THREAD

**Issue by DavidHarar** [AnotherSamWilson/miceforest#77]
Hi, 
First, thank you very much for the great package. Using it lifted my model's KPIs. One thing is, indirectly connected with the `miforest`, is that it uses `light-GBM`.  
It seems that `LGBM` has some compatibility issues with GPU and a separate installation (see [here](https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html)). I tried multiple times to install its GPU version without any success, so I ended up using only one or two iterations because of my large dataset. Is there an option to add compatibility with other boosters like `XGBoost`?

Thank you very much!

**Comment by AnotherSamWilson** [comment]
Unfortunately no. There is another issue to make the underlying imputation model more modular, but it is a deciptively complex problem. Each model has its own way of dealing with categories, shap values, how the data is encoded, etc. It would be a big project, but not an impossible one. 

The underlying model actually used to be sklearn random forests, but they take up a huge amount of memory and are slower. Switching to lightgbm was a big ordeal.

HOWEVER, I would not give up on the lightgbm GPU training. It can be a pain, but what worked for me is installing the wheel version of the package, and simply passing `device_type='gpu'` into the parametes. I know that lightgbm has a bunch of crazy compilation steps that they show in the tutorial, but apparently the wheel comes pre-built with gpu abilities.

**Comment by AnotherSamWilson** [comment]
@DavidHarar Curious if you got lightgbm up and running with gpu.
