### ISSUE TITLE
GPU does not improve performance

### ISSUE THREAD

**Issue by xydisla** [AnotherSamWilson/miceforest#78]
I was able to get lightgbm working with GPU, but it doesn't seem to substantially improve performance (~8% improvement for 64 CPU + GPU vs 64 CPU alone). I've also been monitoring CPU and GPU usage, and it seems like the GPU is only active for brief periods of time during training, and most of the training/imputing time is spent with the CPU being used. 

Interestingly, the GPU takes substantially longer to tune parameters than CPU.

**Comment by AnotherSamWilson** [comment]
I have noticed this phenomenon on small data. GPU can take considerably longer if you do not have many millions of rows in your dataset, and even then it is dependent on datatypes, architecture, etc etc. I'm going to close this, because it does not seem to be miceforest specific.
