### ISSUE TITLE
568 mean_match_candidates > data_subset

### ISSUE THREAD

**Issue by sonj21** [AnotherSamWilson/miceforest#80]
Im trying to use miceforest to impute data for a dataset I am working on with. However, when I first tested the miceforest I had no issues on imputing NaN values. However, when I put in more data to test the miceforest, I kept getting the assertion error of mean_match_candidates > data_subset to all the dataframes I was looking to impute. Can anyone please help me if I should put in a parameter within the imputationkernel?

**Comment by ZSZYoung** [comment]
Drop the features with all value is missing

**Comment by AnotherSamWilson** [comment]
This means that there are some columns that have very, very few non-missing values.
