### ISSUE TITLE
Save large kernel

### ISSUE THREAD

**Issue by ZSZYoung** [AnotherSamWilson/miceforest#84]
I utilized the save_kernel method to store a kernel with 250 iterations. However, it appears that the kernel size exceeds the processing limit, leading to a ValueError: bytesobj cannot exceed 2147483631 bytes. Is there a specific method for saving such a large kernel, or do I need to modify certain kernel settings? I simply want to save the kernel for future diagnostic plotting. 
Thank you for your assistance.

**Comment by AnotherSamWilson** [comment]
This is fixed in the latest update.
