### ISSUE TITLE
pypi version update

### ISSUE THREAD

**Issue by matteobolner** [AnotherSamWilson/miceforest#87]
Good afternoon,
I am trying to install miceforest from pypi but am encountering an error when building blosc;
i suspect it has something to do with #86 .
On pypi the version is still the one from november 2023.
Would it be possible to update it?
Thanks for the amazing package!

**Comment by matteobolner** [comment]
No worries, I asked mainly for adding the package with poetry, meanwhile i can easily manage with installing directly by git.

I am using pandas dataframes, since I use column names to setup the variable schemas and i already use pandas in my pipeline, so I see no reason to use numpy. I have found no problems with pandas so far, which is great!

I actually have a couple of quick questions on the functioning of miceforest compared to the R mice package; should i open another issue, write you an email or ask here?

Sorry for all the questions and thanks again!

**Comment by AnotherSamWilson** [comment]
This has been fixed in the latest major update. blosc2 is no longer a dependency - all parquet stuff is done in `__getstate__` and `__setstate__`.
