### ISSUE TITLE
Import miceforest error

### ISSUE THREAD

**Issue by kestlermai** [AnotherSamWilson/miceforest#89]
How can I resolve the following error when importing the miceforest library after successfully installing it through pip?

> import miceforest as mf
> TypeError: descriptor '__call__' for 'type' objects doesn't apply to a 'property' object

**Comment by AnotherSamWilson** [comment]
Is there any more you can tell me about this error? Are any more lines printed out?

**Comment by AnotherSamWilson** [comment]
Hmmm this looks like an issue with importing dask. If you run this line, do you get the same error:

```from dask.dataframe import DataFrame as dask_DataFrame```

**Comment by kestlermai** [comment]
Yes, the same error occurred.

**Comment by AnotherSamWilson** [comment]
Hmm it might be worth opening an issue with dask. But, nothing I can do here.
